%  Step1_RNA_detection.m
%  Bo Wang, July 2025
close all; clear; clc;

%  DESCRIPTION
%  This script processes time-lapse RNA bursting data. It takes a .tif file
%  containing the RNA signal and a binary probability-mask TIFF generated by
%  Step0_Generate_probability_mask.m, then outputs detected transcriptional
%  spots and single-ROI tracks.
%
%  Output field summary:
%    tracks{n,1}: raw detected track, [frame, row, column, max_pixel_intensity]
%    tracks{n,2}: gap-filled track,
%                 [frame, row, column, max_pixel_intensity,
%                  gaussian_integral, gaussian_amplitude, gaussian_sigma]
%    tracks{n,3}: local RNA-window integrated intensity and background
%    tracks{n,4}: background-corrected RNA-window intensity and background
%    tracks{n,5}: max-pixel intensity after local background subtraction

%% Input image sequence filenames
% Step 1 reads max-projection inputs and writes the resulting *-tracks.mat
% files into the matching processed_data folder for each condition.
data_root = 'D:\ImageData\Supplementary_Imaging_Data\Fig5_Sox2RNA_burst_modeling';

group_info = struct( ...
    'name', {'Untreated', 'JQ1-treated'}, ...
    'max_projection_dir', {fullfile(data_root, 'Untreated', 'max_projection'), ...
                           fullfile(data_root, 'JQ1-treated', 'max_projection')}, ...
    'processed_data_dir', {fullfile(data_root, 'Untreated', 'processed_data'), ...
                           fullfile(data_root, 'JQ1-treated', 'processed_data')} ...
);

filelists = cell(numel(group_info), 1);
num_files = 0;
for group_iter = 1:numel(group_info)
    filelists{group_iter} = dir(fullfile(group_info(group_iter).max_projection_dir, '*-Max.tif'));
    num_files = num_files + numel(filelists{group_iter});
end

filepath_list = cell(num_files, 1);
output_dir_list = cell(num_files, 1);
list_idx = 0;
for group_iter = 1:numel(group_info)
    filelist = filelists{group_iter};
    for file_iter = 1:numel(filelist)
        list_idx = list_idx + 1;
        filepath_list{list_idx} = fullfile(filelist(file_iter).folder, filelist(file_iter).name);
        output_dir_list{list_idx} = group_info(group_iter).processed_data_dir;
    end
end

for cell_iter = 1:length(filepath_list)

    filepath = filepath_list{cell_iter};
    output_dir = output_dir_list{cell_iter};
    if ~isfolder(output_dir)
        mkdir(output_dir);
    end

    % Read the RNA image sequence and the binary probability mask from Step 0.
    img_series = TIFFreader(filepath);

    h = size(img_series, 1);
    w = size(img_series, 2);
    numberOfPages = size(img_series, 3);

    bw = TIFFreader([filepath(1:(end-4)), '-Prob.tif']);
    bw = logical(bw);

    % Read ROI rectangles exported as four corner points per ROI.
    roitable = readtable([filepath(1:(end-4)), '-ROI.txt']);
    roilist = zeros(size(roitable, 1)/4, 4); % xmin, ymin, xmax, ymax
    for i = 1:size(roitable, 1)/4
        roilist(i, 1:2) = roitable{4*(i-1)+1, 1:2};
        roilist(i, 3:4) = roitable{4*(i-1)+3, 1:2};
    end

    %% Detect candidate RNA spots in each frame
    spots = cell(0);
    for frame_iter = 1:numberOfPages
        img = img_series(:, :, frame_iter);
        ccomp = bwconncomp(bw(:, :, frame_iter));

        locs_intensity = zeros(ccomp.NumObjects, 3);
        for i = 1:ccomp.NumObjects
            [m, idx] = max(img(ccomp.PixelIdxList{1, i}));
            locs = ccomp.PixelIdxList{1, i}(idx);
            locs_intensity(i, 3) = m;
            [a, b] = ind2sub(ccomp.ImageSize, locs);
            locs_intensity(i, 1:2) = [a, b];
        end

        spots{frame_iter} = locs_intensity;
    end

    %% Build one RNA intensity track per ROI
    tracks = cell(0);
    for track_iter = 1:size(roilist, 1)
        xmin = roilist(track_iter, 1);
        ymin = roilist(track_iter, 2);
        xmax = roilist(track_iter, 3);
        ymax = roilist(track_iter, 4);

        temp = zeros(numberOfPages, 4);
        for frame_iter = 1:numberOfPages
            idx = find((xmin < spots{frame_iter}(:, 2)) & ...
                       (spots{frame_iter}(:, 2) <= xmax) & ...
                       (ymin < spots{frame_iter}(:, 1)) & ...
                       (spots{frame_iter}(:, 1) <= ymax));
            temp(frame_iter, 1) = frame_iter;
            if ~isempty(idx)
                res = spots{frame_iter}(idx, :);
                [~, i] = max(res(:, 3));
                temp(frame_iter, 2:4) = res(i, :);
            end
        end
        tracks{track_iter, 1} = temp;

        % Fill missing spot positions by carrying edge positions and linearly
        % interpolating internal gaps. The intensity at filled positions is
        % sampled directly from the original image.
        temp_i = temp(:, 4);
        non_zero_indices = find(temp_i ~= 0);
        if isempty(non_zero_indices)
            tracks{track_iter, 2} = temp;
            continue;
        end

        if temp(1, 4) == 0
            temp(1:(non_zero_indices(1)-1), 2) = temp(non_zero_indices(1), 2);
            temp(1:(non_zero_indices(1)-1), 3) = temp(non_zero_indices(1), 3);
            for i = 1:(non_zero_indices(1)-1)
                temp(i, 4) = img_series(temp(i, 2), temp(i, 3), i);
            end
        end

        if temp(end, 4) == 0
            temp((non_zero_indices(end)+1):end, 2) = temp(non_zero_indices(end), 2);
            temp((non_zero_indices(end)+1):end, 3) = temp(non_zero_indices(end), 3);
            for i = (non_zero_indices(end)+1):numberOfPages
                temp(i, 4) = img_series(temp(i, 2), temp(i, 3), i);
            end
        end

        temp(temp(:, 2) == 0, 2) = nan;
        temp(temp(:, 3) == 0, 3) = nan;

        temp = fillmissing(temp, 'linear', 1);
        temp = round(temp);
        for frame_iter = 1:numberOfPages
            if temp(frame_iter, 4) == 0
                temp(frame_iter, 4) = img_series(temp(frame_iter, 2), temp(frame_iter, 3), frame_iter);
            end
        end

        tracks{track_iter, 2} = temp;
    end

    %% Fit a bounded 2D Gaussian around each tracked RNA spot
    for track_iter = 1:size(roilist, 1)
        temp = tracks{track_iter, 2};
        numFrames = size(temp, 1);

        temp(:, 5) = NaN; % Analytical Gaussian integral: 2*pi*A*sigma^2
        temp(:, 6) = NaN; % Fitted Gaussian amplitude
        temp(:, 7) = NaN; % Fitted Gaussian sigma

        for frame_iter = 1:numFrames
            y0 = temp(frame_iter, 2);
            x0 = temp(frame_iter, 3);
            frame = temp(frame_iter, 1);

            % Use a 5-by-5 patch only when the spot is at least two pixels away
            % from the image border.
            if x0 > 2 && y0 > 2 && ...
               x0 < size(img_series, 2)-2 && ...
               y0 < size(img_series, 1)-2

                patch = double(img_series(y0-2:y0+2, x0-2:x0+2, frame));
                [X, Y] = meshgrid(-2:2, -2:2);

                B0 = min(patch(:));
                A0 = max(patch(:)) - B0;
                p0 = [A0, 0, 0, log(1), B0];

                % tanh keeps the fitted center shift within +/-1.5 pixels and
                % sigma within [0.5, 1.5] pixels without requiring constrained
                % optimization.
                gauss2D_bounded = @(p, X, Y) ...
                    p(1) .* exp( ...
                    -((X - 1.5*tanh(p(2))) .^2 + ...
                      (Y - 1.5*tanh(p(3))) .^2) ...
                    ./ (2 * (1.0 + 0.5*tanh(p(4)))^2) ) ...
                    + p(5);

                % L1 loss is used to reduce the effect of occasional bright
                % outlier pixels in the local patch.
                errfun = @(p) sum(abs(gauss2D_bounded(p, X, Y) - patch), 'all');

                options = optimset('Display', 'off');
                p_fit = fminsearch(errfun, p0, options);

                A = p_fit(1);
                sigma = 1.0 + 0.5*tanh(p_fit(4));
                gaussian_integral = 2*pi*A*sigma^2;

                temp(frame_iter, 5) = gaussian_integral;
                temp(frame_iter, 6) = A;
                temp(frame_iter, 7) = sigma;
            end
        end

        tracks{track_iter, 2} = temp;
    end

    %% Calculate window-based RNA intensity for backward compatibility
    % RNA signal is integrated in a 5-by-5 window and background is estimated
    % from the surrounding ring inside a 7-by-7 window.
    rna_width = 2;
    bkg_width = 3;
    for track_iter = 1:size(tracks, 1)
        temp = tracks{track_iter, 2};
        rna_bkg = zeros(numberOfPages, 2);
        rna_bkg_cor = zeros(numberOfPages, 2);
        for frame_iter = 1:numberOfPages
            temp_img = img_series(:, :, frame_iter);
            rna_mask = false(size(temp_img));
            bkg_mask = rna_mask;
            rna_mask(max(temp(frame_iter, 2)-rna_width, 1):min(temp(frame_iter, 2)+rna_width, h), ...
                     max(temp(frame_iter, 3)-rna_width, 1):min(temp(frame_iter, 3)+rna_width, w)) = 1;
            bkg_mask(max(temp(frame_iter, 2)-bkg_width, 1):min(temp(frame_iter, 2)+bkg_width, h), ...
                     max(temp(frame_iter, 3)-bkg_width, 1):min(temp(frame_iter, 3)+bkg_width, w)) = 1;
            bkg_mask = bkg_mask & ~rna_mask;

            bkg = mean(double(temp_img(bkg_mask)));
            rna = sum(double(temp_img(rna_mask)) - bkg);
            rna_bkg(frame_iter, :) = [rna, bkg];
            rna_bkg_cor(frame_iter, :) = [rna, bkg];
        end
        tracks{track_iter, 3} = rna_bkg;
        tracks{track_iter, 4} = rna_bkg_cor;
        tracks{track_iter, 5} = tracks{track_iter, 2}(:, 4) - rna_bkg_cor(:, 2);
    end

    [~, input_name, ~] = fileparts(filepath);
    save(fullfile(output_dir, [input_name, '-tracks.mat']), "spots", "tracks");

end
